"""fix fields

Revision ID: 0b8e44062ac0
Revises: de8535591186
Create Date: 2024-08-23 08:11:41.574653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8e44062ac0'
down_revision: Union[str, None] = 'de8535591186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_class',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('row_created_at', sa.DateTime(), nullable=False),
    sa.Column('row_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.add_column('machine_type', sa.Column('machine_class_uuid', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'machine_type', 'machine_class', ['machine_class_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machine_type', type_='foreignkey')
    op.drop_column('machine_type', 'machine_class_uuid')
    op.drop_table('machine_class')
    # ### end Alembic commands ###
