"""Initial migration

Revision ID: 211af0b464fe
Revises: 
Create Date: 2024-08-18 11:53:02.679935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211af0b464fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_exercise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_type_id', sa.Integer(), nullable=True),
    sa.Column('machine_type', sa.String(length=100), nullable=True),
    sa.Column('activity_id', sa.String(length=64), nullable=True),
    sa.Column('session_date', sa.DateTime(), nullable=True),
    sa.Column('fc_max', sa.Integer(), nullable=True),
    sa.Column('fc_avg', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_exercise')
    op.drop_table('exercise_type')
    # ### end Alembic commands ###
