"""revision

Revision ID: 30db6816ca39
Revises: 5c297a7f4d99
Create Date: 2024-08-22 10:35:27.016538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30db6816ca39'
down_revision: Union[str, None] = '5c297a7f4d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_exercise', sa.Column('exercise_type_uuid', sa.String(length=64), nullable=True))
    op.drop_constraint('session_exercise_ibfk_1', 'session_exercise', type_='foreignkey')
    op.create_foreign_key(None, 'session_exercise', 'exercise_type', ['exercise_type_uuid'], ['uuid'])
    op.drop_column('session_exercise', 'exercise_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_exercise', sa.Column('exercise_type_id', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'session_exercise', type_='foreignkey')
    op.create_foreign_key('session_exercise_ibfk_1', 'session_exercise', 'exercise_type', ['exercise_type_id'], ['uuid'])
    op.drop_column('session_exercise', 'exercise_type_uuid')
    # ### end Alembic commands ###
