"""add moves field

Revision ID: 48881f05940e
Revises: 30db6816ca39
Create Date: 2024-08-22 11:03:45.223805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48881f05940e'
down_revision: Union[str, None] = '30db6816ca39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_exercise', sa.Column('power_avg', sa.Integer(), nullable=True))
    op.add_column('session_exercise', sa.Column('moves', sa.Integer(), nullable=True))
    op.add_column('session_exercise', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_exercise', 'weight')
    op.drop_column('session_exercise', 'moves')
    op.drop_column('session_exercise', 'power_avg')
    # ### end Alembic commands ###
