"""add foreing keys

Revision ID: 5bac9ba21fac
Revises: b2bda73e7bcf
Create Date: 2024-08-18 16:59:08.234790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bac9ba21fac'
down_revision: Union[str, None] = 'b2bda73e7bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_type', sa.Column('exercise_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'machine_type', 'exercise_type', ['exercise_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machine_type', type_='foreignkey')
    op.drop_column('machine_type', 'exercise_type_id')
    # ### end Alembic commands ###
