"""add colories

Revision ID: 6672695a303e
Revises: c04839b02d84
Create Date: 2024-08-25 16:36:07.098606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6672695a303e'
down_revision: Union[str, None] = 'c04839b02d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_exercise', sa.Column('calories', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_exercise', 'calories')
    # ### end Alembic commands ###
