"""change unique id

Revision ID: 92422a58d7ce
Revises: daddbac41553
Create Date: 2024-08-22 09:55:25.532145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92422a58d7ce'
down_revision: Union[str, None] = 'daddbac41553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'session_exercise', ['activity_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_exercise', type_='unique')
    # ### end Alembic commands ###
