"""remove unnecesary fields

Revision ID: de8535591186
Revises: 48881f05940e
Create Date: 2024-08-22 23:06:56.172218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de8535591186'
down_revision: Union[str, None] = '48881f05940e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_exercise_ibfk_3', 'session_exercise', type_='foreignkey')
    op.drop_column('session_exercise', 'exercise_type_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_exercise', sa.Column('exercise_type_uuid', mysql.VARCHAR(length=64), nullable=True))
    op.create_foreign_key('session_exercise_ibfk_3', 'session_exercise', 'exercise_type', ['exercise_type_uuid'], ['uuid'])
    # ### end Alembic commands ###
