"""Initial migration

Revision ID: def6480a665e
Revises: 
Create Date: 2024-08-18 19:39:26.036718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def6480a665e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_type',
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('row_created_at', sa.DateTime(), nullable=False),
    sa.Column('row_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machine_type',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('exercise_type_uuid', sa.String(length=64), nullable=True),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('row_created_at', sa.DateTime(), nullable=False),
    sa.Column('row_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_type_uuid'], ['exercise_type.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('session_exercise',
    sa.Column('exercise_type_id', sa.String(length=64), nullable=True),
    sa.Column('machine_type', sa.String(length=100), nullable=True),
    sa.Column('activity_uuid', sa.String(length=64), nullable=True),
    sa.Column('session_date', sa.DateTime(), nullable=True),
    sa.Column('fc_max', sa.Integer(), nullable=True),
    sa.Column('fc_avg', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('row_created_at', sa.DateTime(), nullable=False),
    sa.Column('row_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_type_id'], ['exercise_type.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_exercise')
    op.drop_table('machine_type')
    op.drop_table('exercise_type')
    # ### end Alembic commands ###
